platform :ios,'9.0'
target 'LianbiHome' do
	pod "Masonry"
	pod 'UMCCommon'
        pod 'UMCSecurityPlugins'
	pod 'UMCShare/Social/WeChat'
	pod 'UMCShare/Social/QQ'
	pod 'UMCShare/Social/Sina'
	pod 'UMCShare/Social/DingDing'
	pod 'SDWebImage', '~> 4.0'
        pod 'AFNetworking', '~> 3.0'
        pod 'MJRefresh'
end
